# Task II: Classical Graph Neural Network (GNN) 
## For Task II, you will use ParticleNet’s data for Quark/Gluon jet classification available [here](https://zenodo.org/records/3164691#.YigdGt9MHrB) with its corresponding description. 
<ul>
    <li> Choose 2 Graph-based architectures of your choice to classify jets as being quarks or gluons. Provide a description on what considerations you have taken to project this point-cloud dataset to a set of interconnected nodes and edges.
    <li> Discuss the resulting performance of the 2 chosen architectures. 
</ul>
<hr>


In [10]:
import numpy as np
from numpy import load

data = load('ParticleNet_jetClassification\\QG_jets_1.npz')
lst = data.files
print (lst)
for item in lst:
    print("Item:")
    print(item)
    print ("Data[Item]")
    print (f"Dimension: {np.ndim(data[item])}")
    print(data[item])
    print ("Shape:")
    print (data[item].shape)

['X', 'y']
Item:
X
Data[Item]
Dimension: 3
[[[ 6.21580243e-01 -8.49013586e-01  5.02133119e+00 -2.11000000e+02]
  [ 6.41751806e-01 -1.25072426e+00  5.44050034e+00  2.11000000e+02]
  [ 2.01318448e-01 -9.03872384e-01  4.90318847e+00  2.20000000e+01]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 3.56561010e-01  1.28450604e+00  1.74690075e+00  2.20000000e+01]
  [ 1.64376978e-01  1.34179128e+00  1.62318700e+00  2.20000000e+01]
  [ 4.29715184e+00  1.00013501e+00  1.88439142e+00  1.30000000e+02]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 1.08500898e+01  1.05767017e+00  6.35388683e+00 -2.11000000e+02]
  [ 4.13482156e-02  7.46948660e-01  6.13804598e+00  2.200

In [11]:
import numpy as np
from numpy import load

data = load('ParticleNet_jetClassification\\QG_jets_2.npz')
lst = data.files
print (lst)
for item in lst:
    print("Item:")
    print(item)
    print ("Data[Item]")
    print (f"Dimension: {np.ndim(data[item])}")
    print(data[item])
    print ("Shape:")
    print (data[item].shape)

['X', 'y']
Item:
X
Data[Item]
Dimension: 3
[[[ 3.93203966e-01  3.50858538e-01  8.55396185e-01  2.20000000e+01]
  [ 2.46338260e+00  1.65702215e-01  7.61525307e-01  2.20000000e+01]
  [ 2.56550934e+00 -5.68774857e-02  7.89741416e-01  2.11000000e+02]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 1.61694863e+00 -1.31621717e+00  9.98804499e-01 -2.11000000e+02]
  [ 1.58885285e-01 -1.51184963e+00  9.30179606e-01  2.20000000e+01]
  [ 1.91738285e+00 -1.84739871e+00  1.31081899e+00 -3.21000000e+02]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 9.02373553e-01  1.26997967e+00  3.01591217e+00  3.21000000e+02]
  [ 7.52902861e-02  9.00624519e-01  3.43656410e+00  2.200

In [12]:
import numpy as np
from numpy import load

data = load('ParticleNet_jetClassification\\QG_jets_3.npz')
lst = data.files
print (lst)
for item in lst:
    print("Item:")
    print(item)
    print ("Data[Item]")
    print (f"Dimension: {np.ndim(data[item])}")
    print(data[item])
    print ("Shape:")
    print (data[item].shape)

['X', 'y']
Item:
X
Data[Item]
Dimension: 3
[[[ 4.07201237e+00  1.09956405e+00  3.85282264e+00  2.11000000e+02]
  [ 7.73380167e-01  7.13987483e-01  3.68545357e+00 -2.11000000e+02]
  [ 1.14809578e-01  5.78924014e-01  3.74063251e+00  2.20000000e+01]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 2.39305753e+00  1.12300153e+00  6.36019987e+00 -2.11000000e+02]
  [ 2.96587205e+00  8.59178845e-01  6.37095677e+00  2.11000000e+02]
  [ 4.78190822e+00  7.45407187e-01  6.31373908e+00  1.30000000e+02]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 6.74573195e-01  1.02391768e+00  2.14886551e+00  2.11000000e+02]
  [ 3.37872916e+00  5.89779017e-01  2.07253851e+00 -2.212

In [13]:
import numpy as np
from numpy import load

data = load('ParticleNet_jetClassification\\QG_jets_withbc_0.npz')
lst = data.files
print (lst)
for item in lst:
    print("Item:")
    print(item)
    print ("Data[Item]")
    print (f"Dimension: {np.ndim(data[item])}")
    print(data[item])
    print ("Shape:")
    print (data[item].shape)

['X', 'y']
Item:
X
Data[Item]
Dimension: 3
[[[ 9.86502732e-01 -1.35386410e+00  2.64458483e-01  2.20000000e+01]
  [ 1.05703896e+00 -1.34115771e+00  2.19554508e-01  2.21200000e+03]
  [ 6.21758834e-01 -1.29731387e+00  2.74126482e-01  2.20000000e+01]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 2.25822279e+00 -8.77790734e-01  4.93749866e+00 -2.11000000e+02]
  [ 1.05114111e+01 -1.06668930e+00  5.34817384e+00  2.11200000e+03]
  [ 4.82717145e+00 -1.06442943e+00  5.25285614e+00 -2.11000000e+02]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 1.39930755e-01  1.25928787e+00  1.70230491e+00  2.20000000e+01]
  [ 6.17137998e-01  1.64929615e+00  1.96346964e+00  2.200

In [ ]:
import numpy as np
import torch
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import GCNConv
import torch.nn.functional as F

# Step 1: Load the data
data = np.load('ParticleNet_jetClassification\\QG_jets_1.npz')
node_features = data['X']  # Shape: (100000, M, 4)
labels = data['y']  # Shape: (100000,)

# Define a function to create edges (fully connected graph for simplicity)
def create_edge_index(num_nodes):
    row = []
    col = []
    for i in range(num_nodes):
        for j in range(num_nodes):
            if i != j:  # Avoid self-loops
                row.append(i)
                col.append(j)
    return torch.tensor([row, col], dtype=torch.long)

# Convert dataset into a list of graphs
graphs = []
for i in range(len(node_features)):
    x = torch.tensor(node_features[i], dtype=torch.float)  # Node features for jet i
    y = torch.tensor(labels[i], dtype=torch.long)  # Label for jet i
    edge_index = create_edge_index(x.shape[0])  # Fully connected graph
    graphs.append(Data(x=x, edge_index=edge_index, y=y))

# Create a DataLoader for batching
batch_size = 32
loader = DataLoader(graphs, batch_size=batch_size, shuffle=True)

# Step 2: Define the GCN model
class GCN(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(input_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, output_dim)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

# Step 3: Initialize the model, optimizer, and loss function
input_dim = 4  # Each particle has 4 features: pt, rapidity, azimuthal angle, pdgid
hidden_dim = 64
output_dim = 2  # Binary classification: quark (1) or gluon (0)

model = GCN(input_dim, hidden_dim, output_dim)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
criterion = torch.nn.CrossEntropyLoss()

# Step 4: Train the model
def train():
    model.train()
    total_loss = 0
    for batch in loader:
        optimizer.zero_grad()
        out = model(batch)
        loss = criterion(out, batch.y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)

# Step 5: Evaluate the model
def test():
    model.eval()
    correct = 0
    total = 0
    for batch in loader:
        out = model(batch)
        _, pred = out.max(dim=1)
        correct += pred.eq(batch.y).sum().item()
        total += batch.y.size(0)
    return correct / total

# Training loop
for epoch in range(20):  # Reduce epochs for testing; increase as needed
    loss = train()
    acc = test()
    print(f'Epoch {epoch}, Loss: {loss:.4f}, Accuracy: {acc:.4f}')

c:\Users\vmuno\OneDrive\Desktop\GSOC25\GSOC25\Lib\site-packages\torch_geometric\deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


ValueError: Expected input batch_size (4288) to match target batch_size (32).

: 

In [1]:
import numpy as np
import torch
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import GCNConv, global_mean_pool
import torch.nn.functional as F

# Step 1: Load the data
data = np.load('ParticleNet_jetClassification\\QG_jets_1.npz')
node_features = data['X']  # Shape: (100000, M, 4)
labels = data['y']  # Shape: (100000,)

# Define a function to create edges (fully connected graph for simplicity)
def create_edge_index(num_nodes):
    row = []
    col = []
    for i in range(num_nodes):
        for j in range(num_nodes):
            if i != j:  # Avoid self-loops
                row.append(i)
                col.append(j)
    return torch.tensor([row, col], dtype=torch.long)

# Convert dataset into a list of graphs
graphs = []
for i in range(len(node_features)):
    x = torch.tensor(node_features[i], dtype=torch.float)  # Node features for jet i
    y = torch.tensor(labels[i], dtype=torch.long)  # Label for jet i
    edge_index = create_edge_index(x.shape[0])  # Fully connected graph
    graphs.append(Data(x=x, edge_index=edge_index, y=y))

# Create a DataLoader for batching
batch_size = 32
loader = DataLoader(graphs, batch_size=batch_size, shuffle=True)

# Step 2: Define the GCN model
class GCN(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(input_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, hidden_dim)
        self.fc = torch.nn.Linear(hidden_dim, output_dim)  # Fully connected layer for graph-level classification

    def forward(self, data):
        x, edge_index, batch = data.x, data.edge_index, data.batch
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        x = F.relu(x)
        x = global_mean_pool(x, batch)  # Aggregate node features into graph-level features
        x = self.fc(x)  # Final classification layer
        return F.log_softmax(x, dim=1)

# Step 3: Initialize the model, optimizer, and loss function
input_dim = 4  # Each particle has 4 features: pt, rapidity, azimuthal angle, pdgid
hidden_dim = 64
output_dim = 2  # Binary classification: quark (1) or gluon (0)

model = GCN(input_dim, hidden_dim, output_dim)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
criterion = torch.nn.CrossEntropyLoss()

# Step 4: Train the model
def train():
    model.train()
    total_loss = 0
    for batch in loader:
        optimizer.zero_grad()
        out = model(batch)  # Output shape: (batch_size, output_dim)
        loss = criterion(out, batch.y)  # batch.y shape: (batch_size,)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)

# Step 5: Evaluate the model
def test():
    model.eval()
    correct = 0
    total = 0
    for batch in loader:
        out = model(batch)
        _, pred = out.max(dim=1)
        correct += pred.eq(batch.y).sum().item()
        total += batch.y.size(0)
    return correct / total

# Training loop
for epoch in range(20):  # Reduce epochs for testing; increase as needed
    loss = train()
    acc = test()
    print(f'Epoch {epoch}, Loss: {loss:.4f}, Accuracy: {acc:.4f}')

c:\Users\vmuno\OneDrive\Desktop\GSOC25\GSOC25\Lib\site-packages\torch_geometric\deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


Epoch 0, Loss: 0.6141, Accuracy: 0.6756
Epoch 1, Loss: 0.6041, Accuracy: 0.6745
Epoch 2, Loss: 0.6039, Accuracy: 0.6853
Epoch 3, Loss: 0.6035, Accuracy: 0.6838
Epoch 4, Loss: 0.6031, Accuracy: 0.6813
Epoch 5, Loss: 0.6021, Accuracy: 0.6770
Epoch 6, Loss: 0.6032, Accuracy: 0.6543
Epoch 7, Loss: 0.6035, Accuracy: 0.6721
Epoch 8, Loss: 0.6028, Accuracy: 0.6698
Epoch 9, Loss: 0.6028, Accuracy: 0.6705
Epoch 10, Loss: 0.6024, Accuracy: 0.6729
Epoch 11, Loss: 0.6033, Accuracy: 0.6739
Epoch 12, Loss: 0.6028, Accuracy: 0.6756
Epoch 13, Loss: 0.6033, Accuracy: 0.6849
Epoch 14, Loss: 0.6038, Accuracy: 0.6822
Epoch 15, Loss: 0.6037, Accuracy: 0.6845
Epoch 16, Loss: 0.6027, Accuracy: 0.6822
Epoch 17, Loss: 0.6029, Accuracy: 0.6574
Epoch 18, Loss: 0.6029, Accuracy: 0.6834
Epoch 19, Loss: 0.6034, Accuracy: 0.6845


In [2]:
# Save the trained model locally
torch.save(model.state_dict(), 'gcn_model.pth')  # Save only the model's parameters
print("Model saved to gcn_model.pth")

Model saved to gcn_model.pth


Here’s a **line-by-line breakdown** of the code:

---

### **Imports**


In [ ]:
import numpy as np
import torch
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import GCNConv, global_mean_pool
import torch.nn.functional as F

1. **`numpy`**: Used to load and manipulate the `.npz` dataset.
2. **`torch`**: Core PyTorch library for defining and training models.
3. **`torch_geometric.data.Data`**: Represents a single graph with nodes, edges, and features.
4. **`torch_geometric.data.DataLoader`**: Handles batching and shuffling of multiple graphs.
5. **`torch_geometric.nn.GCNConv`**: Implements a Graph Convolutional Network (GCN) layer.
6. **`torch_geometric.nn.global_mean_pool`**: Aggregates node features into a single graph-level representation.
7. **`torch.nn.functional`**: Provides activation functions like `relu` and `log_softmax`.

---

### **Step 1: Load the Data**


In [ ]:
data = np.load('ParticleNet_jetClassification\\QG_jets_1.npz')
node_features = data['X']  # Shape: (100000, M, 4)
labels = data['y']  # Shape: (100000,)

8. **`np.load`**: Loads the `.npz` file containing the dataset.
9. **`node_features`**: Extracts the particle-level features for each jet. Shape `(100000, M, 4)`:
   - `100000`: Number of jets.
   - `M`: Maximum number of particles in a jet (zero-padded).
   - `4`: Features per particle (`pt`, `rapidity`, `azimuthal angle`, `pdgid`).
10. **`labels`**: Extracts the jet-level labels (`0` for gluon, `1` for quark). Shape `(100000,)`.

---

### **Define a Function to Create Edges**


In [ ]:
def create_edge_index(num_nodes):
    row = []
    col = []
    for i in range(num_nodes):
        for j in range(num_nodes):
            if i != j:  # Avoid self-loops
                row.append(i)
                col.append(j)
    return torch.tensor([row, col], dtype=torch.long)

11. **`create_edge_index`**: Creates a fully connected graph for a jet:
    - **`row` and `col`**: Define the source and target nodes for each edge.
    - **`i != j`**: Avoids self-loops (edges from a node to itself).
12. **`torch.tensor`**: Converts the edge list into a PyTorch tensor of shape `(2, num_edges)`.

---

### **Convert Dataset into a List of Graphs**


In [ ]:
graphs = []
for i in range(len(node_features)):
    x = torch.tensor(node_features[i], dtype=torch.float)  # Node features for jet i
    y = torch.tensor(labels[i], dtype=torch.long)  # Label for jet i
    edge_index = create_edge_index(x.shape[0])  # Fully connected graph
    graphs.append(Data(x=x, edge_index=edge_index, y=y))

13. **`graphs`**: A list to store graph representations of each jet.
14. **`x`**: Converts the particle features of jet `i` into a PyTorch tensor.
15. **`y`**: Converts the label of jet `i` into a PyTorch tensor.
16. **`edge_index`**: Creates a fully connected graph for the particles in jet `i`.
17. **`Data`**: Combines `x`, `edge_index`, and `y` into a graph object.
18. **`graphs.append`**: Adds the graph to the list.

---

### **Create a DataLoader for Batching**


In [ ]:
batch_size = 32
loader = DataLoader(graphs, batch_size=batch_size, shuffle=True)

19. **`batch_size`**: Number of graphs (jets) per batch.
20. **`DataLoader`**: Handles batching and shuffling of the graphs for training.

---

### **Step 2: Define the GCN Model**


In [ ]:
class GCN(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(input_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, hidden_dim)
        self.fc = torch.nn.Linear(hidden_dim, output_dim)  # Fully connected layer for graph-level classification

21. **`GCN`**: Defines the Graph Convolutional Network model.
22. **`GCNConv`**: Two GCN layers for learning node-level features.
23. **`torch.nn.Linear`**: A fully connected layer for graph-level classification.



In [ ]:
    def forward(self, data):
        x, edge_index, batch = data.x, data.edge_index, data.batch
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        x = F.relu(x)
        x = global_mean_pool(x, batch)  # Aggregate node features into graph-level features
        x = self.fc(x)  # Final classification layer
        return F.log_softmax(x, dim=1)

24. **`forward`**: Defines the forward pass of the model.
25. **`data.x`**: Node features.
26. **`data.edge_index`**: Graph structure (edges).
27. **`data.batch`**: Batch information (which nodes belong to which graph).
28. **`global_mean_pool`**: Aggregates node features into a single graph-level feature.
29. **`F.log_softmax`**: Outputs probabilities for each class (quark or gluon).

---

### **Step 3: Initialize the Model, Optimizer, and Loss Function**


In [ ]:
input_dim = 4  # Each particle has 4 features: pt, rapidity, azimuthal angle, pdgid
hidden_dim = 64
output_dim = 2  # Binary classification: quark (1) or gluon (0)

model = GCN(input_dim, hidden_dim, output_dim)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
criterion = torch.nn.CrossEntropyLoss()

30. **`input_dim`**: Number of input features per particle.
31. **`hidden_dim`**: Number of hidden units in the GCN layers.
32. **`output_dim`**: Number of output classes (binary classification).
33. **`Adam`**: Optimizer for training the model.
34. **`CrossEntropyLoss`**: Loss function for classification tasks.

---

### **Step 4: Train the Model**


In [ ]:
def train():
    model.train()
    total_loss = 0
    for batch in loader:
        optimizer.zero_grad()
        out = model(batch)  # Output shape: (batch_size, output_dim)
        loss = criterion(out, batch.y)  # batch.y shape: (batch_size,)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)

35. **`train`**: Defines the training loop.
36. **`model.train()`**: Sets the model to training mode.
37. **`optimizer.zero_grad()`**: Clears gradients from the previous step.
38. **`model(batch)`**: Runs the forward pass for the batch.
39. **`loss.backward()`**: Computes gradients for the model parameters.
40. **`optimizer.step()`**: Updates the model parameters.
41. **`total_loss`**: Accumulates the loss for the batch.

---

### **Step 5: Evaluate the Model**


In [ ]:
def test():
    model.eval()
    correct = 0
    total = 0
    for batch in loader:
        out = model(batch)
        _, pred = out.max(dim=1)
        correct += pred.eq(batch.y).sum().item()
        total += batch.y.size(0)
    return correct / total

42. **`test`**: Defines the evaluation loop.
43. **`model.eval()`**: Sets the model to evaluation mode.
44. **`out.max(dim=1)`**: Gets the predicted class for each graph.
45. **`pred.eq(batch.y)`**: Compares predictions with ground truth labels.
46. **`correct`**: Counts the number of correct predictions.
47. **`total`**: Tracks the total number of graphs.

---

### **Training Loop**


In [ ]:
for epoch in range(20):  # Reduce epochs for testing; increase as needed
    loss = train()
    acc = test()
    print(f'Epoch {epoch}, Loss: {loss:.4f}, Accuracy: {acc:.4f}')

48. **`range(20)`**: Runs the training loop for 20 epochs.
49. **`train()`**: Trains the model for one epoch.
50. **`test()`**: Evaluates the model after each epoch.
51. **`print`**: Displays the loss and accuracy for each epoch.

---

Let me know if you need further clarification!