# Task II: Classical Graph Neural Network (GNN) 
## For Task II, you will use ParticleNet’s data for Quark/Gluon jet classification available [here](https://zenodo.org/records/3164691#.YigdGt9MHrB) with its corresponding description. 
<ul>
    <li> Choose 2 Graph-based architectures of your choice to classify jets as being quarks or gluons. Provide a description on what considerations you have taken to project this point-cloud dataset to a set of interconnected nodes and edges.
    <li> Discuss the resulting performance of the 2 chosen architectures. 
</ul>
<hr>


# Data Downloading and Loading

In [10]:
import numpy as np
from numpy import load

data = load('ParticleNet_jetClassification\\QG_jets_1.npz')
lst = data.files
print (lst)
for item in lst:
    print("Item:")
    print(item)
    print ("Data[Item]")
    print (f"Dimension: {np.ndim(data[item])}")
    print(data[item])
    print ("Shape:")
    print (data[item].shape)

['X', 'y']
Item:
X
Data[Item]
Dimension: 3
[[[ 6.21580243e-01 -8.49013586e-01  5.02133119e+00 -2.11000000e+02]
  [ 6.41751806e-01 -1.25072426e+00  5.44050034e+00  2.11000000e+02]
  [ 2.01318448e-01 -9.03872384e-01  4.90318847e+00  2.20000000e+01]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 3.56561010e-01  1.28450604e+00  1.74690075e+00  2.20000000e+01]
  [ 1.64376978e-01  1.34179128e+00  1.62318700e+00  2.20000000e+01]
  [ 4.29715184e+00  1.00013501e+00  1.88439142e+00  1.30000000e+02]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 1.08500898e+01  1.05767017e+00  6.35388683e+00 -2.11000000e+02]
  [ 4.13482156e-02  7.46948660e-01  6.13804598e+00  2.200

In [11]:
import numpy as np
from numpy import load

data = load('ParticleNet_jetClassification\\QG_jets_2.npz')
lst = data.files
print (lst)
for item in lst:
    print("Item:")
    print(item)
    print ("Data[Item]")
    print (f"Dimension: {np.ndim(data[item])}")
    print(data[item])
    print ("Shape:")
    print (data[item].shape)

['X', 'y']
Item:
X
Data[Item]
Dimension: 3
[[[ 3.93203966e-01  3.50858538e-01  8.55396185e-01  2.20000000e+01]
  [ 2.46338260e+00  1.65702215e-01  7.61525307e-01  2.20000000e+01]
  [ 2.56550934e+00 -5.68774857e-02  7.89741416e-01  2.11000000e+02]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 1.61694863e+00 -1.31621717e+00  9.98804499e-01 -2.11000000e+02]
  [ 1.58885285e-01 -1.51184963e+00  9.30179606e-01  2.20000000e+01]
  [ 1.91738285e+00 -1.84739871e+00  1.31081899e+00 -3.21000000e+02]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 9.02373553e-01  1.26997967e+00  3.01591217e+00  3.21000000e+02]
  [ 7.52902861e-02  9.00624519e-01  3.43656410e+00  2.200

In [12]:
import numpy as np
from numpy import load

data = load('ParticleNet_jetClassification\\QG_jets_3.npz')
lst = data.files
print (lst)
for item in lst:
    print("Item:")
    print(item)
    print ("Data[Item]")
    print (f"Dimension: {np.ndim(data[item])}")
    print(data[item])
    print ("Shape:")
    print (data[item].shape)

['X', 'y']
Item:
X
Data[Item]
Dimension: 3
[[[ 4.07201237e+00  1.09956405e+00  3.85282264e+00  2.11000000e+02]
  [ 7.73380167e-01  7.13987483e-01  3.68545357e+00 -2.11000000e+02]
  [ 1.14809578e-01  5.78924014e-01  3.74063251e+00  2.20000000e+01]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 2.39305753e+00  1.12300153e+00  6.36019987e+00 -2.11000000e+02]
  [ 2.96587205e+00  8.59178845e-01  6.37095677e+00  2.11000000e+02]
  [ 4.78190822e+00  7.45407187e-01  6.31373908e+00  1.30000000e+02]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 6.74573195e-01  1.02391768e+00  2.14886551e+00  2.11000000e+02]
  [ 3.37872916e+00  5.89779017e-01  2.07253851e+00 -2.212

In [13]:
import numpy as np
from numpy import load

data = load('ParticleNet_jetClassification\\QG_jets_withbc_0.npz')
lst = data.files
print (lst)
for item in lst:
    print("Item:")
    print(item)
    print ("Data[Item]")
    print (f"Dimension: {np.ndim(data[item])}")
    print(data[item])
    print ("Shape:")
    print (data[item].shape)

['X', 'y']
Item:
X
Data[Item]
Dimension: 3
[[[ 9.86502732e-01 -1.35386410e+00  2.64458483e-01  2.20000000e+01]
  [ 1.05703896e+00 -1.34115771e+00  2.19554508e-01  2.21200000e+03]
  [ 6.21758834e-01 -1.29731387e+00  2.74126482e-01  2.20000000e+01]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 2.25822279e+00 -8.77790734e-01  4.93749866e+00 -2.11000000e+02]
  [ 1.05114111e+01 -1.06668930e+00  5.34817384e+00  2.11200000e+03]
  [ 4.82717145e+00 -1.06442943e+00  5.25285614e+00 -2.11000000e+02]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 1.39930755e-01  1.25928787e+00  1.70230491e+00  2.20000000e+01]
  [ 6.17137998e-01  1.64929615e+00  1.96346964e+00  2.200

# GCN - Code, Explaination and Performamce Analysis

## Considerations made

After downloading and loading data to train a **Graph Neural Network (GCN)**, for quark/gluon jet classification, several considerations must be taken into account to ensure the data is properly prepared and suitable for training. Below are the key considerations:

### **1. Dataset Format**
- **Structure**:
  - The dataset should be structured in a way that supports graph representation.
  - For your dataset:
    - **Node Features (`X`)**: Each particle in a jet is represented as a node with features like `pt`, `rapidity`, `azimuthal angle`, and `pdgid`.
    - **Labels (`y`)**: Each jet (graph) is labeled as `0` (gluon) or `1` (quark).
- **File Format**:
  - The dataset is stored in an `.npz` file, which is a compressed format for NumPy arrays. This is efficient for storing large datasets.

### **2. Data Preprocessing**
- **Zero-Padding**:
  - Since jets have varying numbers of particles, the dataset is padded to a maximum multiplicity (`M`) to ensure uniform shape. (This is where we use the information that if there are non-uniform number of particles, we will be padding the nest with 0s till we match the size M)
  - Consideration: Ensure that padded particles (zero-particles) are excluded or handled appropriately during graph construction. (We need to ensure that we handle the 0s appropriately to ensure model's accuracy and general nature)

- **Normalization**

- **Edge Definition**

### **3. Graph Representation**
- **Nodes**:
  - Each particle (of M) in a jet is treated as a node, with its features (`pt`, `rapidity`, `azimuthal angle`, `pdgid`) as the node attributes.
- **Edges**:
  - A fully connected graph is created for simplicity, where all particles are connected to each other.
  - Consideration: Fully connected graphs may introduce noise. Using physics-based edges (e.g., proximity in ΔR space) can improve performance.
- **Graph-Level Labels**:
  - Each graph (jet) is assigned a single label (`0` for gluon, `1` for quark).

### **4. Data Splitting**
- **Training, Validation, and Test Sets**:
  - The dataset should be split into training, validation, and test sets to evaluate the model's performance.
  - Consideration: Ensure the splits are stratified to maintain the balance between quark and gluon jets in each set.

### **5. Data Loading**
- **Batching**:
  - Use a `DataLoader` to batch multiple graphs together for efficient training.
  - Consideration: Ensure the `batch_size` is appropriate for your system's memory.
- **Shuffling**:
  - Shuffle the dataset during training to prevent the model from learning the order of the data.

### **6. Computational Considerations**
- **Memory Usage**:
  - Large datasets with fully connected graphs can consume significant memory. Consider reducing the number of edges or using sparse representations.
- **GPU Acceleration**:
  - If using a GPU, ensure the data is moved to the GPU (`.to(device)`) for faster computation.

### **7. Handling Imbalanced Data**
- **Class Balance**:
  - The dataset is balanced (50% quark jets, 50% gluon jets), so no additional steps are needed for class balancing.
- **Class Weights**:
  - If the dataset were imbalanced, we could use class weights in the loss function to handle the imbalance.

### **8. Data Integrity**
- **Validation**:
  - Ensure the dataset is free of errors, such as:
    - Missing or corrupted data.
    - Incorrect labels.
  - Example: Verify that padded particles have zero features and are excluded during graph construction.

### **9. Scalability**
- **Large Datasets**:
  - If the dataset is too large to fit into memory, we can consider:
    - Loading the data in chunks.
    - Using a streaming data pipeline.

### Summary of Considerations
| **Aspect**              | **Consideration**                                                                 |
|--------------------------|-----------------------------------------------------------------------------------|
| Dataset Format           | Ensure the dataset supports graph representation (nodes, edges, labels).         |
| Preprocessing            | Normalize features, handle zero-padded particles, and define meaningful edges.   |
| Graph Representation     | Use nodes for particles, edges for relationships, and graph-level labels.        |
| Data Splitting           | Split into training, validation, and test sets with balanced classes.            |
| Data Loading             | Use batching and shuffling for efficient training.                               |
| Memory Usage             | Optimize graph size and batch size for memory constraints.                       |
| Physics-Based Features   | Use domain knowledge to define features and edges (e.g., ΔR, energy thresholds). |
| Class Balance            | Ensure balanced classes or use class weights if imbalanced.                      |
| Data Integrity           | Validate the dataset for missing or corrupted data.                              |
| Scalability              | Handle large datasets with chunking or streaming.                                |



---

## How GCN is working on the Data

### **Dataset Overview**
The dataset consists of:
1. **Graph Description**:
   - The entire graph is treated as either a gluon jet or a quark jet.
    - **Nodes**: Particles in the jet.
    - **Edges**: Relationships between particles (e.g., fully connected or based on physics-based criteria like ΔR).

2. **Node Features (`X`)**:
   - Shape: `(100000, M, 4)` where:
     - `100000`: Number of jets.
     - `M`: Maximum number of particles in a jet (zero-padded).
     - `4`: Features per particle (`pt`, `rapidity`, `azimuthal angle`, `pdgid`).
   - Each particle in a jet is treated as a **node** in the graph.

3. **Labels (`y`)**:
   - Shape: `(100000,)` where each jet is labeled as:
     - `0`: Gluon jet.
     - `1`: Quark jet.
   - Each jet is treated as a **graph**, and the task is **graph-level classification**.
     

### **1. Graph Construction**
Each jet is converted into a graph using the `torch_geometric.data.Data` class:
- **Nodes**: Represent particles in the jet, with features like `pt`, `rapidity`, `azimuthal angle`, and `pdgid`.
- **Edges**: A fully connected graph is created for simplicity (all particles are connected to each other). This is defined by the `create_edge_index` function.

For example:
- A jet with 3 particles (`M=3`) will have:
  - **Nodes**: 3 nodes, each with 4 features.
  - **Edges**: Fully connected graph with 6 edges (excluding self-loops).

### **2. Node Feature Transformation (GCN Layers)**
The GCN model consists of two **GCNConv** layers. These layers perform the following operations:

#### **Step 1: First GCN Layer**


In [ ]:
x = self.conv1(x, edge_index)
x = F.relu(x)

- **Input**:
  - `x`: Node features (shape: `[num_nodes, input_dim]`).
  - `edge_index`: Graph structure (edges).
- **Operation**:
  - Each node aggregates features from its neighbors (defined by `edge_index`) and transforms them using a learnable weight matrix.
  - The result is passed through a ReLU activation function to introduce non-linearity.
- **Output**:
  - Updated node features (shape: `[num_nodes, hidden_dim]`).

#### **Step 2: Second GCN Layer**


In [ ]:
x = self.conv2(x, edge_index)
x = F.relu(x)

- **Input**:
  - Node features from the first GCN layer.
- **Operation**:
  - Similar to the first layer, but transforms the features into a new space.
- **Output**:
  - Final node features (shape: `[num_nodes, hidden_dim]`).

### **3. Graph-Level Pooling**
After the GCN layers, the node features are aggregated into a single graph-level representation using **global mean pooling**:


In [ ]:
x = global_mean_pool(x, batch)

- **Input**:
  - `x`: Node features (shape: `[num_nodes, hidden_dim]`).
  - `batch`: A tensor that maps each node to its corresponding graph in the batch.
- **Operation**:
  - For each graph, the mean of the node features is computed.
- **Output**:
  - Graph-level features (shape: `[batch_size, hidden_dim]`).

### **4. Graph-Level Classification**
The graph-level features are passed through a fully connected layer to predict the class (quark or gluon):


In [ ]:
x = self.fc(x)
return F.log_softmax(x, dim=1)

- **Input**:
  - Graph-level features (shape: `[batch_size, hidden_dim]`).
- **Operation**:
  - The fully connected layer maps the graph-level features to the output dimension (`output_dim=2` for binary classification).
  - The `log_softmax` function converts the output into log probabilities for each class.
- **Output**:
  - Predicted probabilities for each graph in the batch (shape: `[batch_size, 2]`).

### **5. Training**
During training, the model learns to minimize the **cross-entropy loss** between the predicted probabilities and the true labels:


In [ ]:
loss = criterion(out, batch.y)

- **Input**:
  - `out`: Predicted probabilities (shape: `[batch_size, 2]`).
  - `batch.y`: True labels for each graph in the batch (shape: `[batch_size]`).
- **Operation**:
  - The loss function computes how far the predictions are from the true labels.
- **Output**:
  - A scalar loss value, which is used to update the model parameters.

### **6. Evaluation**
During evaluation, the model predicts the class for each graph and computes the accuracy:


In [ ]:
_, pred = out.max(dim=1)
correct += pred.eq(batch.y).sum().item()

- **`out.max(dim=1)`**: Gets the predicted class (in this case: Binary Classification -> Gluon jet or Quark jet) (index of the maximum probability).
- **`pred.eq(batch.y)`**: Compares predictions with true labels.
- **Accuracy**: The ratio of correct predictions to the total number of graphs.

### **Summary of Workflow**
1. **Graph Construction**:
   - Each jet is represented as a graph with particles as nodes and edges connecting them.
2. **Node Feature Transformation**:
   - GCN layers aggregate and transform node features based on the graph structure.
3. **Graph-Level Pooling**:
   - Node features are aggregated into a single graph-level representation.
4. **Classification**:
   - The graph-level features are used to predict the class (quark or gluon).
5. **Training**:
   - The model learns by minimizing the cross-entropy loss.
6. **Evaluation**:
   - The model's performance is evaluated using accuracy.

### Why GCN Works for This Dataset
- **Particle Interactions**: The GCN captures relationships between particles in a jet through the graph structure. (Since we are connecting all the paritlces as either a fully connected graph or a physics-based critera)
- **Feature Aggregation**: The GCN layers aggregate particle-level features to learn meaningful jet-level representations. (The properties of all the particles measured are considered to predict the type of jet)
- **Graph-Level Pooling**: The pooling operation ensures that the model outputs a single prediction for each jet.

---

## Code

In [1]:
import numpy as np
import torch
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import GCNConv, global_mean_pool
import torch.nn.functional as F

# Step 1: Load the data
data = np.load('ParticleNet_jetClassification\\QG_jets_1.npz')
node_features = data['X']  # Shape: (100000, M, 4)
labels = data['y']  # Shape: (100000,)

# Define a function to create edges (fully connected graph for simplicity)
def create_edge_index(num_nodes):
    row = []
    col = []
    for i in range(num_nodes):
        for j in range(num_nodes):
            if i != j:  # Avoid self-loops
                row.append(i)
                col.append(j)
    return torch.tensor([row, col], dtype=torch.long)

# Convert dataset into a list of graphs
graphs = []
for i in range(len(node_features)):
    x = torch.tensor(node_features[i], dtype=torch.float)  # Node features for jet i
    y = torch.tensor(labels[i], dtype=torch.long)  # Label for jet i
    edge_index = create_edge_index(x.shape[0])  # Fully connected graph
    graphs.append(Data(x=x, edge_index=edge_index, y=y))

# Create a DataLoader for batching
batch_size = 32
loader = DataLoader(graphs, batch_size=batch_size, shuffle=True)

# Step 2: Define the GCN model
class GCN(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(input_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, hidden_dim)
        self.fc = torch.nn.Linear(hidden_dim, output_dim)  # Fully connected layer for graph-level classification

    def forward(self, data):
        x, edge_index, batch = data.x, data.edge_index, data.batch
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        x = F.relu(x)
        x = global_mean_pool(x, batch)  # Aggregate node features into graph-level features
        x = self.fc(x)  # Final classification layer
        return F.log_softmax(x, dim=1)

# Step 3: Initialize the model, optimizer, and loss function
input_dim = 4  # Each particle has 4 features: pt, rapidity, azimuthal angle, pdgid
hidden_dim = 64
output_dim = 2  # Binary classification: quark (1) or gluon (0)

model = GCN(input_dim, hidden_dim, output_dim)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
criterion = torch.nn.CrossEntropyLoss()

# Step 4: Train the model
def train():
    model.train()
    total_loss = 0
    for batch in loader:
        optimizer.zero_grad()
        out = model(batch)  # Output shape: (batch_size, output_dim)
        loss = criterion(out, batch.y)  # batch.y shape: (batch_size,)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)

# Step 5: Evaluate the model
def test():
    model.eval()
    correct = 0
    total = 0
    for batch in loader:
        out = model(batch)
        _, pred = out.max(dim=1)
        correct += pred.eq(batch.y).sum().item()
        total += batch.y.size(0)
    return correct / total

# Training loop
for epoch in range(20):  # Reduce epochs for testing; increase as needed
    loss = train()
    acc = test()
    print(f'Epoch {epoch}, Loss: {loss:.4f}, Accuracy: {acc:.4f}')

c:\Users\vmuno\OneDrive\Desktop\GSOC25\GSOC25\Lib\site-packages\torch_geometric\deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


Epoch 0, Loss: 0.6141, Accuracy: 0.6756
Epoch 1, Loss: 0.6041, Accuracy: 0.6745
Epoch 2, Loss: 0.6039, Accuracy: 0.6853
Epoch 3, Loss: 0.6035, Accuracy: 0.6838
Epoch 4, Loss: 0.6031, Accuracy: 0.6813
Epoch 5, Loss: 0.6021, Accuracy: 0.6770
Epoch 6, Loss: 0.6032, Accuracy: 0.6543
Epoch 7, Loss: 0.6035, Accuracy: 0.6721
Epoch 8, Loss: 0.6028, Accuracy: 0.6698
Epoch 9, Loss: 0.6028, Accuracy: 0.6705
Epoch 10, Loss: 0.6024, Accuracy: 0.6729
Epoch 11, Loss: 0.6033, Accuracy: 0.6739
Epoch 12, Loss: 0.6028, Accuracy: 0.6756
Epoch 13, Loss: 0.6033, Accuracy: 0.6849
Epoch 14, Loss: 0.6038, Accuracy: 0.6822
Epoch 15, Loss: 0.6037, Accuracy: 0.6845
Epoch 16, Loss: 0.6027, Accuracy: 0.6822
Epoch 17, Loss: 0.6029, Accuracy: 0.6574
Epoch 18, Loss: 0.6029, Accuracy: 0.6834
Epoch 19, Loss: 0.6034, Accuracy: 0.6845


In [2]:
# Save the trained model locally
torch.save(model.state_dict(), 'gcn_model.pth')  # Save only the model's parameters
print("Model saved to gcn_model.pth")

Model saved to gcn_model.pth


In [3]:
# Laod the model for inference or further training
model_loaded = GCN(input_dim, hidden_dim, output_dim)  # Initialize the model architecture
model.load_state_dict(torch.load('gcn_model.pth'))  # Load the saved parameters
model.eval()  # Set the model to evaluation mode
print("Model loaded from gcn_model.pth")

Model loaded from gcn_model.pth


---

## Code Explaination

### **Imports**


In [ ]:
import numpy as np
import torch
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import GCNConv, global_mean_pool
import torch.nn.functional as F

1. **`numpy`**: Used to load and manipulate the `.npz` dataset.
2. **`torch`**: Core PyTorch library for defining and training models.
3. **`torch_geometric.data.Data`**: Represents a single graph with nodes, edges, and features.
4. **`torch_geometric.data.DataLoader`**: Handles batching and shuffling of multiple graphs.
5. **`torch_geometric.nn.GCNConv`**: Implements a Graph Convolutional Network (GCN) layer.
6. **`torch_geometric.nn.global_mean_pool`**: Aggregates node features into a single graph-level representation.
7. **`torch.nn.functional`**: Provides activation functions like `relu` and `log_softmax`.


### **Step 1: Load the Data**


In [ ]:
data = np.load('ParticleNet_jetClassification\\QG_jets_1.npz')
node_features = data['X']  # Shape: (100000, M, 4)
labels = data['y']  # Shape: (100000,)

8. **`np.load`**: Loads the `.npz` file containing the dataset.
9. **`node_features`**: Extracts the particle-level features for each jet. Shape `(100000, M, 4)`:
   - `100000`: Number of jets.
   - `M`: Maximum number of particles in a jet (zero-padded).
   - `4`: Features per particle (`pt`, `rapidity`, `azimuthal angle`, `pdgid`).
10. **`labels`**: Extracts the jet-level labels (`0` for gluon, `1` for quark). Shape `(100000,)`.

### **Define a Function to Create Edges**


In [ ]:
def create_edge_index(num_nodes):
    row = []
    col = []
    for i in range(num_nodes):
        for j in range(num_nodes):
            if i != j:  # Avoid self-loops
                row.append(i)
                col.append(j)
    return torch.tensor([row, col], dtype=torch.long)

11. **`create_edge_index`**: Creates a fully connected graph for a jet:
    - **`row` and `col`**: Define the source and target nodes for each edge.
    - **`i != j`**: Avoids self-loops (edges from a node to itself). (Doing this might name the node, lose it's own context and just consider that of the edges) (We can explore if keeping the context i.e. allowing slef loops and observing how that affects the accuracy of the model, thus making cool discoveries about the perticles constituing qluon and quark jets, their properties as individual particles and as a gorup )
12. **`torch.tensor`**: Converts the edge list into a PyTorch tensor of shape `(2, num_edges)`.

### **Convert Dataset into a List of Graphs**


In [ ]:
graphs = []
for i in range(len(node_features)):
    x = torch.tensor(node_features[i], dtype=torch.float)  # Node features for jet i
    y = torch.tensor(labels[i], dtype=torch.long)  # Label for jet i
    edge_index = create_edge_index(x.shape[0])  # Fully connected graph
    graphs.append(Data(x=x, edge_index=edge_index, y=y))

13. **`graphs`**: A list to store graph representations of each jet.
14. **`x`**: Converts the particle features of jet `i` into a PyTorch tensor.
15. **`y`**: Converts the label of jet `i` into a PyTorch tensor.
16. **`edge_index`**: Creates a fully connected graph for the particles in jet `i`.
17. **`Data`**: Combines `x`, `edge_index`, and `y` into a graph object.
18. **`graphs.append`**: Adds the graph to the list.

### **Create a DataLoader for Batching**


In [ ]:
batch_size = 32
loader = DataLoader(graphs, batch_size=batch_size, shuffle=True)

19. **`batch_size`**: Number of graphs (jets) per batch.
20. **`DataLoader`**: Handles batching and shuffling of the graphs for training.

### **Step 2: Define the GCN Model**


In [ ]:
class GCN(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(input_dim, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, hidden_dim)
        self.fc = torch.nn.Linear(hidden_dim, output_dim)  # Fully connected layer for graph-level classification

21. **`GCN`**: Defines the Graph Convolutional Network model.
22. **`GCNConv`**: Two GCN layers for learning node-level features.
23. **`torch.nn.Linear`**: A fully connected layer for graph-level classification.



In [ ]:
    def forward(self, data):
        x, edge_index, batch = data.x, data.edge_index, data.batch
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        x = F.relu(x)
        x = global_mean_pool(x, batch)  # Aggregate node features into graph-level features
        x = self.fc(x)  # Final classification layer
        return F.log_softmax(x, dim=1)

24. **`forward`**: Defines the forward pass of the model.
25. **`data.x`**: Node features.
26. **`data.edge_index`**: Graph structure (edges).
27. **`data.batch`**: Batch information (which nodes belong to which graph).
28. **`global_mean_pool`**: Aggregates node features into a single graph-level feature.
29. **`F.log_softmax`**: Outputs probabilities for each class (quark or gluon).

### **Step 3: Initialize the Model, Optimizer, and Loss Function**


In [ ]:
input_dim = 4  # Each particle has 4 features: pt, rapidity, azimuthal angle, pdgid
hidden_dim = 64
output_dim = 2  # Binary classification: quark (1) or gluon (0)

model = GCN(input_dim, hidden_dim, output_dim)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
criterion = torch.nn.CrossEntropyLoss()

30. **`input_dim`**: Number of input features per particle.
31. **`hidden_dim`**: Number of hidden units in the GCN layers.
32. **`output_dim`**: Number of output classes (binary classification).
33. **`Adam`**: Optimizer for training the model.
34. **`CrossEntropyLoss`**: Loss function for classification tasks.

### **Step 4: Train the Model**


In [ ]:
def train():
    model.train()
    total_loss = 0
    for batch in loader:
        optimizer.zero_grad()
        out = model(batch)  # Output shape: (batch_size, output_dim)
        loss = criterion(out, batch.y)  # batch.y shape: (batch_size,)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)

35. **`train`**: Defines the training loop.
36. **`model.train()`**: Sets the model to training mode.
37. **`optimizer.zero_grad()`**: Clears gradients from the previous step.
38. **`model(batch)`**: Runs the forward pass for the batch.
39. **`loss.backward()`**: Computes gradients for the model parameters.
40. **`optimizer.step()`**: Updates the model parameters.
41. **`total_loss`**: Accumulates the loss for the batch.


### **Step 5: Evaluate the Model**


In [ ]:
def test():
    model.eval()
    correct = 0
    total = 0
    for batch in loader:
        out = model(batch)
        _, pred = out.max(dim=1)
        correct += pred.eq(batch.y).sum().item()
        total += batch.y.size(0)
    return correct / total

42. **`test`**: Defines the evaluation loop.
43. **`model.eval()`**: Sets the model to evaluation mode.
44. **`out.max(dim=1)`**: Gets the predicted class for each graph.
45. **`pred.eq(batch.y)`**: Compares predictions with ground truth labels.
46. **`correct`**: Counts the number of correct predictions.
47. **`total`**: Tracks the total number of graphs.


### **Training Loop**


In [ ]:
for epoch in range(20):  # Reduce epochs for testing; increase as needed
    loss = train()
    acc = test()
    print(f'Epoch {epoch}, Loss: {loss:.4f}, Accuracy: {acc:.4f}')

48. **`range(20)`**: Runs the training loop for 20 epochs.
49. **`train()`**: Trains the model for one epoch.
50. **`test()`**: Evaluates the model after each epoch.
51. **`print`**: Displays the loss and accuracy for each epoch.



---

## Performance Analysis

In [ ]:
import matplotlib.pyplot as plt

# As we can see, in the code above, i missed adding the train_losses and val_accuracies lists to
# store the training loss and validation accuracy for each epoch.
# We shall not forget this in the next model training.

# Filepath to the GCN output file
file_path = 'GCN_output.txt'

# Initialize empty lists to store training losses and validation accuracies
train_losses = []
val_accuracies = []

# Read the file and extract the values
with open(file_path, 'r') as file:
    for line in file:
        # Split the line into components
        parts = line.strip().split(", ")
        if len(parts) == 3:  # Ensure the line has the expected format
            # Extract the loss and accuracy values
            loss = float(parts[1].split(": ")[1])  # Extract the value after "Loss: "
            accuracy = float(parts[2].split(": ")[1])  # Extract the value after "Accuracy: "
            
            # Append the values to the respective lists
            train_losses.append(loss)
            val_accuracies.append(accuracy)

# Print the extracted lists
print("Train_losses:", train_losses)
print("val_accuracies:", val_accuracies)

# Plot training loss
plt.figure(figsize=(10, 5))
plt.plot(range(1, len(train_losses) + 1), train_losses, label='Training Loss', color='blue')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training Loss Over Epochs')
plt.legend()
plt.grid()
plt.show()

# Plot validation accuracy
plt.figure(figsize=(10, 5))
plt.plot(range(1, len(val_accuracies) + 1), val_accuracies, label='Validation Accuracy', color='green')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Validation Accuracy Over Epochs')
plt.legend()
plt.grid()
plt.show()

NameError: name 'train_losses' is not defined

<Figure size 1000x500 with 0 Axes>

: 

### How to Evaluate Performance
1. **Training Loss**:
   - Monitor the loss printed during training. It should decrease steadily over epochs.
   - If the loss stagnates or increases, consider adjusting the learning rate or model architecture.

2. **Accuracy**:
   - The accuracy printed during each epoch reflects how well the model is performing on the dataset.
   - If the accuracy is low (e.g., close to 50%), the model might not be learning effectively.

3. **Overfitting**:
   - If the training loss decreases but the accuracy does not improve, the model might be overfitting.
   - To address this, consider adding regularization (e.g., dropout) or using a validation set.


### Tips to Improve Performance
1. **Edge Definition**:
   - The current implementation uses a fully connected graph for simplicity. Defining edges based on physics-based criteria (e.g., ΔR between particles) might improve performance.
   - Maybe by including self-loops, we might get better results

2. **Hyperparameter Tuning**:
   - Experiment with different values for:
     - Learning rate (`lr`): Try values like `0.001`, `0.005`, or `0.01`.
     - Hidden dimension (`hidden_dim`): Increase or decrease the number of hidden units (e.g., `32`, `128`).
     - Batch size (`batch_size`): Try smaller or larger batch sizes (e.g., `16`, `64`).



---

---

# GAT - Code, Explaination and Performance Analysis

## Considerations Made

The provided code for training a **Graph Attention Network (GAT)** on the quark/gluon jet classification dataset incorporates several considerations to ensure the model is trained effectively and the results are saved for later use. Below is a detailed breakdown of the considerations made in the code:

(The considerations made here are very similar to those made for GCN)

### **1. Dataset Preparation**
#### **Graph Representation**
- **Nodes**:
  - Each particle in a jet is treated as a node, with features like `pt`, `rapidity`, `azimuthal angle`, and `pdgid`.
  - The node features are extracted from the dataset (`X`) and converted into PyTorch tensors.
- **Edges**:
  - A fully connected graph is created for each jet, where all particles are connected to each other.
  - This is implemented using the `create_edge_index` function, which avoids self-loops (`i != j`).
  - **Consideration**: Fully connected graphs are simple but may introduce noise. Physics-based edge definitions (e.g., based on ΔR) could improve performance.

#### **Batching**
- The dataset is converted into a list of graphs using `torch_geometric.data.Data`, where each graph represents a jet.
- A `DataLoader` is used to batch multiple graphs together for efficient training.
- **Consideration**: The batch size is set to `32`, which balances computational efficiency and memory usage.


### **2. Model Architecture**
#### **Graph Attention Network (GAT)**
- **Attention Mechanism**:
  - The GAT layers (`GATConv`) dynamically assign weights to edges, allowing the model to focus on the most important relationships between particles.
- **Multiple Attention Heads**:
  - The first GAT layer uses `4` attention heads (`heads=4`) to capture diverse relationships between particles.
  - The outputs of the attention heads are concatenated (`concat=True`).
- **Graph-Level Pooling**:
  - After the GAT layers, `global_mean_pool` is used to aggregate node features into a single graph-level representation.
  - This ensures that the model outputs one prediction per graph (jet).
- **Fully Connected Layer**:
  - A fully connected layer maps the graph-level features to the output dimension (`2` for binary classification: quark or gluon).
- **Activation Function**:
  - The Exponential Linear Unit (ELU) activation function is used after each GAT layer to introduce non-linearity.


### **3. Training and Evaluation**
#### **Training Loop**
- The model is trained for `20` epochs, with the following steps in each epoch:
  - **Forward Pass**: The model processes the batch of graphs and outputs predictions.
  - **Loss Calculation**: The cross-entropy loss is computed between the predictions and the true labels.
  - **Backward Pass**: Gradients are computed, and the model parameters are updated using the Adam optimizer.
- **Consideration**: The learning rate is set to `0.01`, and weight decay (`5e-4`) is used to regularize the model and prevent overfitting.

#### **Evaluation**
- After each epoch, the model is evaluated on the validation set:
  - The accuracy is computed as the ratio of correct predictions to the total number of graphs.
- **Consideration**: The evaluation ensures that the model is generalizing well to unseen data.

### **4. Metric Tracking**
- **Training Loss**:
  - The loss for each epoch is stored in the `train_losses` list.
- **Validation Accuracy**:
  - The accuracy for each epoch is stored in the `val_accuracies` list.
- **Consideration**: Tracking these metrics allows for performance analysis and visualization after training.

### **5. Saving Results**
#### **Model Parameters**
- The trained model's parameters are saved to a file (`gan_model.pth`) using `torch.save`.
- **Consideration**: Saving only the model's parameters (state dictionary) is more efficient and flexible than saving the entire model.

#### **Training Metrics**
- The `train_losses` and `val_accuracies` lists are saved to a `.txt` file (`training_metrics.txt`) for later analysis.
- **Consideration**: Saving metrics ensures that the training process can be reviewed and visualized without rerunning the training.

### **6. Scalability**
- **Batching**:
  - The use of a `DataLoader` ensures that the model can handle large datasets efficiently by processing them in batches.
- **Memory Usage**:
  - The batch size (`32`) and hidden dimension (`64`) are chosen to balance memory usage and computational efficiency.

### **7. Domain-Specific Considerations**
- **Physics-Based Features**:
  - The node features (`pt`, `rapidity`, `azimuthal angle`, `pdgid`) are meaningful for distinguishing quark and gluon jets.
- **Balanced Dataset**:
  - The dataset is balanced (50% quark jets, 50% gluon jets), so no additional steps are needed for class balancing.

### **8. Reproducibility**
- **Saving Results**:
  - The model parameters and training metrics are saved, ensuring that the results can be reproduced and analyzed later.
- **Logging**:
  - The training loop prints the loss and accuracy for each epoch, providing a clear record of the training process.


### **Summary of Considerations**
| **Aspect**              | **Consideration**                                                                 |
|--------------------------|-----------------------------------------------------------------------------------|
| Dataset Representation   | Nodes represent particles; edges define relationships (fully connected graph).   |
| Model Architecture       | GAT layers with attention mechanisms and multiple heads for better feature learning. |
| Training Process         | Tracks training loss and validation accuracy for performance monitoring.          |
| Regularization           | Weight decay (`5e-4`) prevents overfitting.                                       |
| Metric Saving            | Saves training metrics (`train_losses`, `val_accuracies`) for later analysis.     |
| Model Saving             | Saves model parameters (`gan_model.pth`) for reuse without retraining.            |
| Scalability              | Uses batching and efficient graph representation to handle large datasets.        |
| Domain Knowledge         | Leverages physics-based features (`pt`, `rapidity`, etc.) for meaningful learning.|

---


## How GAT is working on the Data

The **Graph Attention Network (GAT)** works on the quark/gluon jet classification dataset by leveraging **attention mechanisms** to dynamically assign importance to the relationships (edges) between particles (nodes) in a jet (graph). Here's a detailed explanation of how the GAT processes the data:

### **1. Dataset Representation**
The dataset is represented as a collection of graphs, where:
- **Nodes**: Represent particles in a jet, with features like `pt`, `rapidity`, `azimuthal angle`, and `pdgid`.
- **Edges**: Represent relationships between particles. For simplicity, a fully connected graph is used, meaning every particle is connected to every other particle in the jet.
- **Graph-Level Labels**: Each graph (jet) is labeled as `0` (gluon) or `1` (quark).

### **2. GAT Architecture**
The GAT model consists of the following components:

#### **a. GAT Layers (`GATConv`)**
- **Purpose**: Transform node features by aggregating information from neighboring nodes, with attention weights determining the importance of each neighbor.
- **How It Works**:
  1. For each node, the GAT computes attention coefficients for all its neighbors based on their features.
  2. These coefficients are normalized (using softmax) to ensure they sum to 1.
  3. The node's new feature is computed as a weighted sum of its neighbors' features, where the weights are the attention coefficients.
- **Multiple Attention Heads**:
  - The first GAT layer uses multiple attention heads (`heads=4`) to capture diverse relationships between particles.
  - The outputs of the attention heads are concatenated to form the updated node features.

#### **b. Graph-Level Pooling (`global_mean_pool`)**
- **Purpose**: Aggregate node features into a single graph-level representation.
- **How It Works**:
  - For each graph, the mean of all node features is computed. This ensures that the model outputs one feature vector per graph.

#### **c. Fully Connected Layer**
- **Purpose**: Map the graph-level features to the output dimension (`2` for binary classification: quark or gluon).
- **How It Works**:
  - The graph-level features are passed through a fully connected layer, which outputs the logits for each class.

### **3. Forward Pass**
The GAT processes the data in the following steps:

#### **Step 1: Input**
- **Node Features (`x`)**: Each node (particle) has 4 features: `pt`, `rapidity`, `azimuthal angle`, and `pdgid`.
- **Edge Index (`edge_index`)**: Defines the graph structure (which nodes are connected).

#### **Step 2: First GAT Layer**


In [ ]:
x = self.gat1(x, edge_index)
x = F.elu(x)

- **Input**:
  - `x`: Node features (shape: `[num_nodes, input_dim]`).
  - `edge_index`: Graph structure (edges).
- **Operation**:
  - The GAT layer computes attention coefficients for each edge and updates the node features based on the weighted sum of its neighbors' features.
  - The updated features are passed through an ELU activation function to introduce non-linearity.
- **Output**:
  - Updated node features (shape: `[num_nodes, hidden_dim * heads]`).

#### **Step 3: Second GAT Layer**


In [ ]:
x = self.gat2(x, edge_index)
x = F.elu(x)

- **Input**:
  - Node features from the first GAT layer.
- **Operation**:
  - Similar to the first layer, but with a single attention head (`heads=1`) and no concatenation.
- **Output**:
  - Final node features (shape: `[num_nodes, hidden_dim]`).

#### **Step 4: Graph-Level Pooling**


In [ ]:
x = global_mean_pool(x, batch)

- **Input**:
  - Node features (shape: `[num_nodes, hidden_dim]`).
  - `batch`: A tensor that maps each node to its corresponding graph in the batch.
- **Operation**:
  - For each graph, the mean of the node features is computed to produce a single graph-level feature vector.
- **Output**:
  - Graph-level features (shape: `[batch_size, hidden_dim]`).

#### **Step 5: Fully Connected Layer**


In [ ]:
x = self.fc(x)
return F.log_softmax(x, dim=1)

- **Input**:
  - Graph-level features (shape: `[batch_size, hidden_dim]`).
- **Operation**:
  - The fully connected layer maps the graph-level features to the output dimension (`2` for binary classification).
  - The `log_softmax` function converts the logits into log probabilities for each class.
- **Output**:
  - Predicted probabilities for each graph in the batch (shape: `[batch_size, 2]`).


### **4. Training**
During training, the model learns to minimize the **cross-entropy loss** between the predicted probabilities and the true labels:


In [ ]:
loss = criterion(out, batch.y)

- **Input**:
  - `out`: Predicted probabilities (shape: `[batch_size, 2]`).
  - `batch.y`: True labels for each graph in the batch (shape: `[batch_size]`).
- **Operation**:
  - The loss function computes how far the predictions are from the true labels.
- **Output**:
  - A scalar loss value, which is used to update the model parameters.

### **5. Evaluation**
During evaluation, the model predicts the class for each graph and computes the accuracy:


In [ ]:
_, pred = out.max(dim=1)
correct += pred.eq(batch.y).sum().item()

- **`out.max(dim=1)`**: Gets the predicted class (index of the maximum probability).
- **`pred.eq(batch.y)`**: Compares predictions with true labels.
- **Accuracy**: The ratio of correct predictions to the total number of graphs.

### **6. Why GAT Works for This Dataset**
- **Dynamic Edge Weights**:
  - The attention mechanism allows the GAT to assign different importance to different edges, enabling it to focus on the most relevant particle relationships.
- **Multiple Attention Heads**:
  - Multiple attention heads capture diverse relationships between particles, improving the model's ability to learn complex patterns.
- **Graph-Level Pooling**:
  - Aggregating node features into a graph-level representation ensures that the model outputs a single prediction for each jet.


### **Summary**
The GAT processes the dataset by:
1. Representing each jet as a graph with particles as nodes and their relationships as edges.
2. Using attention mechanisms to dynamically assign importance to edges.
3. Aggregating node features into a graph-level representation.
4. Predicting the class (quark or gluon) for each graph.

---

## Code

In [ ]:
import numpy as np
import torch
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import GATConv, global_mean_pool
import torch.nn.functional as F

# Step 1: Load the data
data = np.load('ParticleNet_jetClassification\\QG_jets_1.npz')
node_features = data['X']  # Shape: (100000, M, 4)
labels = data['y']  # Shape: (100000,)

# Define a function to create edges (fully connected graph for simplicity)
def create_edge_index(num_nodes):
    row = []
    col = []
    for i in range(num_nodes):
        for j in range(num_nodes):
            if i != j:  # Avoid self-loops
                row.append(i)
                col.append(j)
    return torch.tensor([row, col], dtype=torch.long)

# Convert dataset into a list of graphs
graphs = []
for i in range(len(node_features)):
    x = torch.tensor(node_features[i], dtype=torch.float)  # Node features for jet i
    y = torch.tensor(labels[i], dtype=torch.long)  # Label for jet i
    edge_index = create_edge_index(x.shape[0])  # Fully connected graph
    graphs.append(Data(x=x, edge_index=edge_index, y=y))

# Create a DataLoader for batching
batch_size = 32
loader = DataLoader(graphs, batch_size=batch_size, shuffle=True)

# Step 2: Define the GAT model
class GAT(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, heads=4):
        super(GAT, self).__init__()
        self.gat1 = GATConv(input_dim, hidden_dim, heads=heads, concat=True)
        self.gat2 = GATConv(hidden_dim * heads, hidden_dim, heads=1, concat=False)
        self.fc = torch.nn.Linear(hidden_dim, output_dim)  # Fully connected layer for graph-level classification

    def forward(self, data):
        x, edge_index, batch = data.x, data.edge_index, data.batch
        x = self.gat1(x, edge_index)
        x = F.elu(x)  # Use ELU activation for GAT
        x = self.gat2(x, edge_index)
        x = F.elu(x)
        x = global_mean_pool(x, batch)  # Aggregate node features into graph-level features
        x = self.fc(x)  # Final classification layer
        return F.log_softmax(x, dim=1)

# Step 3: Initialize the model, optimizer, and loss function
input_dim = 4  # Each particle has 4 features: pt, rapidity, azimuthal angle, pdgid
hidden_dim = 64
output_dim = 2  # Binary classification: quark (1) or gluon (0)

model = GAT(input_dim, hidden_dim, output_dim, heads=4)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
criterion = torch.nn.CrossEntropyLoss()

# Step 4: Train the model
def train():
    model.train()
    total_loss = 0
    for batch in loader:
        optimizer.zero_grad()
        out = model(batch)  # Output shape: (batch_size, output_dim)
        loss = criterion(out, batch.y)  # batch.y shape: (batch_size,)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)

# Step 5: Evaluate the model
def test():
    model.eval()
    correct = 0
    total = 0
    for batch in loader:
        out = model(batch)
        _, pred = out.max(dim=1)
        correct += pred.eq(batch.y).sum().item()
        total += batch.y.size(0)
    return correct / total


# Initialize lists to store metrics
train_losses = []
val_accuracies = []

# Training loop
for epoch in range(20):  # Adjust the number of epochs as needed
    loss = train()  # Train the model for one epoch
    acc = test()  # Evaluate the model on the validation set
    train_losses.append(loss)  # Store the training loss
    val_accuracies.append(acc)  # Store the validation accuracy
    print(f'Epoch {epoch}, Loss: {loss:.4f}, Accuracy: {acc:.4f}')

# Save the trained model locally
torch.save(model.state_dict(), 'gan_model.pth')  # Save only the model's parameters
print("Model saved to gan_model.pth")

# Save train_losses and val_accuracies to a .txt file
with open('training_metrics.txt', 'w') as f:
    f.write("Train Losses:\n")
    f.write(", ".join(map(str, train_losses)) + "\n")
    f.write("Validation Accuracies:\n")
    f.write(", ".join(map(str, val_accuracies)) + "\n")

print("Training metrics saved to training_metrics.txt")

c:\Users\vmuno\OneDrive\Desktop\GSOC25\GSOC25\Lib\site-packages\torch_geometric\deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


Epoch 0, Loss: 1.0182, Accuracy: 0.6235
Epoch 1, Loss: 0.7033, Accuracy: 0.5001
Epoch 2, Loss: 0.9849, Accuracy: 0.5001
Epoch 3, Loss: 0.7288, Accuracy: 0.5000
Epoch 4, Loss: 0.8144, Accuracy: 0.5000
Epoch 5, Loss: 0.7537, Accuracy: 0.5000
Epoch 6, Loss: 0.7915, Accuracy: 0.5000
Epoch 7, Loss: 0.8520, Accuracy: 0.5000
Epoch 8, Loss: 0.9297, Accuracy: 0.5000
Epoch 9, Loss: 0.7117, Accuracy: 0.5000
Epoch 10, Loss: 1.0586, Accuracy: 0.5893
Epoch 11, Loss: 0.7047, Accuracy: 0.5000
Epoch 12, Loss: 0.7265, Accuracy: 0.5000


## Code Explanation 

### **Imports**


In [ ]:
import numpy as np
import torch
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import GATConv, global_mean_pool
import torch.nn.functional as F

1. **`numpy`**: Used to load and manipulate the `.npz` dataset.
2. **`torch`**: Core PyTorch library for defining and training models.
3. **`torch_geometric.data.Data`**: Represents a single graph with nodes, edges, and features.
4. **`torch_geometric.data.DataLoader`**: Handles batching and shuffling of multiple graphs.
5. **`torch_geometric.nn.GATConv`**: Implements the Graph Attention Network (GAT) layer.
6. **`torch_geometric.nn.global_mean_pool`**: Aggregates node features into a single graph-level representation.
7. **`torch.nn.functional`**: Provides activation functions like `elu` and `log_softmax`.

### **Step 1: Load the Data**


In [ ]:
data = np.load('ParticleNet_jetClassification\\QG_jets_1.npz')
node_features = data['X']  # Shape: (100000, M, 4)
labels = data['y']  # Shape: (100000,)

8. **`np.load`**: Loads the `.npz` file containing the dataset.
9. **`node_features`**: Extracts the particle-level features for each jet. Shape `(100000, M, 4)`:
   - `100000`: Number of jets.
   - `M`: Maximum number of particles in a jet (zero-padded).
   - `4`: Features per particle (`pt`, `rapidity`, `azimuthal angle`, `pdgid`).
10. **`labels`**: Extracts the jet-level labels (`0` for gluon, `1` for quark). Shape `(100000,)`.

### **Define a Function to Create Edges**


In [ ]:
def create_edge_index(num_nodes):
    row = []
    col = []
    for i in range(num_nodes):
        for j in range(num_nodes):
            if i != j:  # Avoid self-loops
                row.append(i)
                col.append(j)
    return torch.tensor([row, col], dtype=torch.long)

11. **`create_edge_index`**: Creates a fully connected graph for a jet:
    - **`row` and `col`**: Define the source and target nodes for each edge.
    - **`i != j`**: Avoids self-loops (edges from a node to itself).
12. **`torch.tensor`**: Converts the edge list into a PyTorch tensor of shape `(2, num_edges)`.

### **Convert Dataset into a List of Graphs**


In [ ]:
graphs = []
for i in range(len(node_features)):
    x = torch.tensor(node_features[i], dtype=torch.float)  # Node features for jet i
    y = torch.tensor(labels[i], dtype=torch.long)  # Label for jet i
    edge_index = create_edge_index(x.shape[0])  # Fully connected graph
    graphs.append(Data(x=x, edge_index=edge_index, y=y))

13. **`graphs`**: A list to store graph representations of each jet.
14. **`x`**: Converts the particle features of jet `i` into a PyTorch tensor.
15. **`y`**: Converts the label of jet `i` into a PyTorch tensor.
16. **`edge_index`**: Creates a fully connected graph for the particles in jet `i`.
17. **`Data`**: Combines `x`, `edge_index`, and `y` into a graph object.
18. **`graphs.append`**: Adds the graph to the list.


### **Create a DataLoader for Batching**


In [ ]:
batch_size = 32
loader = DataLoader(graphs, batch_size=batch_size, shuffle=True)

19. **`batch_size`**: Number of graphs (jets) per batch.
20. **`DataLoader`**: Handles batching and shuffling of the graphs for training.

### **Step 2: Define the GAT Model**


In [ ]:
class GAT(torch.nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, heads=4):
        super(GAT, self).__init__()
        self.gat1 = GATConv(input_dim, hidden_dim, heads=heads, concat=True)
        self.gat2 = GATConv(hidden_dim * heads, hidden_dim, heads=1, concat=False)
        self.fc = torch.nn.Linear(hidden_dim, output_dim)  # Fully connected layer for graph-level classification

21. **`GAT`**: Defines the Graph Attention Network model.
22. **`GATConv`**: Two GAT layers for learning node-level features.
23. **`torch.nn.Linear`**: A fully connected layer for graph-level classification.



In [ ]:
    def forward(self, data):
        x, edge_index, batch = data.x, data.edge_index, data.batch
        x = self.gat1(x, edge_index)
        x = F.elu(x)  # Use ELU activation for GAT
        x = self.gat2(x, edge_index)
        x = F.elu(x)
        x = global_mean_pool(x, batch)  # Aggregate node features into graph-level features
        x = self.fc(x)  # Final classification layer
        return F.log_softmax(x, dim=1)

24. **`forward`**: Defines the forward pass of the model.
25. **`data.x`**: Node features.
26. **`data.edge_index`**: Graph structure (edges).
27. **`data.batch`**: Batch information (which nodes belong to which graph).
28. **`global_mean_pool`**: Aggregates node features into a single graph-level feature.
29. **`F.log_softmax`**: Outputs probabilities for each class (quark or gluon).

### **Step 3: Initialize the Model, Optimizer, and Loss Function**


In [ ]:
input_dim = 4  # Each particle has 4 features: pt, rapidity, azimuthal angle, pdgid
hidden_dim = 64
output_dim = 2  # Binary classification: quark (1) or gluon (0)

model = GAT(input_dim, hidden_dim, output_dim, heads=4)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
criterion = torch.nn.CrossEntropyLoss()

30. **`input_dim`**: Number of input features per particle.
31. **`hidden_dim`**: Number of hidden units in the GAT layers.
32. **`output_dim`**: Number of output classes (binary classification).
33. **`Adam`**: Optimizer for training the model.
34. **`CrossEntropyLoss`**: Loss function for classification tasks.
### **Step 4: Train the Model**


In [ ]:
def train():
    model.train()
    total_loss = 0
    for batch in loader:
        optimizer.zero_grad()
        out = model(batch)  # Output shape: (batch_size, output_dim)
        loss = criterion(out, batch.y)  # batch.y shape: (batch_size,)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)

35. **`train`**: Defines the training loop.
36. **`model.train()`**: Sets the model to training mode.
37. **`optimizer.zero_grad()`**: Clears gradients from the previous step.
38. **`model(batch)`**: Runs the forward pass for the batch.
39. **`loss.backward()`**: Computes gradients for the model parameters.
40. **`optimizer.step()`**: Updates the model parameters.
41. **`total_loss`**: Accumulates the loss for the batch.

### **Step 5: Evaluate the Model**


In [ ]:
def test():
    model.eval()
    correct = 0
    total = 0
    for batch in loader:
        out = model(batch)
        _, pred = out.max(dim=1)
        correct += pred.eq(batch.y).sum().item()
        total += batch.y.size(0)
    return correct / total

42. **`test`**: Defines the evaluation loop.
43. **`model.eval()`**: Sets the model to evaluation mode.
44. **`out.max(dim=1)`**: Gets the predicted class for each graph.
45. **`pred.eq(batch.y)`**: Compares predictions with ground truth labels.
46. **Accuracy**: The ratio of correct predictions to the total number of graphs.

### **Training Loop**


In [ ]:
for epoch in range(20):  # Adjust the number of epochs as needed
    loss = train()  # Train the model for one epoch
    acc = test()  # Evaluate the model on the validation set
    train_losses.append(loss)  # Store the training loss
    val_accuracies.append(acc)  # Store the validation accuracy
    print(f'Epoch {epoch}, Loss: {loss:.4f}, Accuracy: {acc:.4f}')

47. **`range(20)`**: Runs the training loop for 20 epochs.
48. **`train()`**: Trains the model for one epoch.
49. **`test()`**: Evaluates the model after each epoch.
50. **`train_losses`**: Stores the training loss for each epoch.
51. **`val_accuracies`**: Stores the validation accuracy for each epoch.


### **Saving the Model**


In [ ]:
torch.save(model.state_dict(), 'gan_model.pth')  # Save only the model's parameters
print("Model saved to gan_model.pth")

52. **`torch.save`**: Saves the model's parameters to a file (`gan_model.pth`).


### **Saving Metrics**


In [ ]:
with open('training_metrics.txt', 'w') as f:
    f.write("Train Losses:\n")
    f.write(", ".join(map(str, train_losses)) + "\n")
    f.write("Validation Accuracies:\n")
    f.write(", ".join(map(str, val_accuracies)) + "\n")

53. **`open`**: Opens a file to save the training metrics.
54. **`map(str, train_losses)`**: Converts the loss values to strings for saving.
55. **`f.write`**: Writes the metrics to the file.


## Performance Analysis

In [ ]:
import matplotlib.pyplot as plt

# Plot training loss
plt.figure(figsize=(10, 5))
plt.plot(range(1, len(train_losses) + 1), train_losses, label='Training Loss', color='blue')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training Loss Over Epochs')
plt.legend()
plt.grid()
plt.show()

# Plot validation accuracy
plt.figure(figsize=(10, 5))
plt.plot(range(1, len(val_accuracies) + 1), val_accuracies, label='Validation Accuracy', color='green')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Validation Accuracy Over Epochs')
plt.legend()
plt.grid()
plt.show()